COMMENTS = [
    "Incredible plot and mind-blowing visuals!",
    "Absolutely terrible. Waste of time.",
    "The director did a great job!",
    "Can't believe how much I loved this!",
    "Worst movie ever made.",
    "10/10 would recommend to a friend.",
    "I fell asleep halfway through.",
    "Such a classic, never gets old.",
    "The characters were very flat.",
    "Oscar-worthy performance!",
    "Overrated and boring.",
    "Underrated gem!",
    "The soundtrack was amazing.",
    "The pacing was too slow.",
    "Too much CGI ruined it.",
    "Realistic and emotional.",
    "Felt like a rollercoaster.",
    "This movie changed my life.",
    "Predictable ending.",
    "Great twist at the end!",
    "Brilliant cinematography.",
    "Weak script but strong acting.",
    "Wouldn't watch it again.",
    "Surprisingly good!",
    "Left the theatre amazed.",
    "Cliché and uninspired.",
    "Beautiful visuals, bad story.",
    "Fun for the whole family.",
    "I laughed, I cried, I cheered.",
    "Plot holes everywhere!",
    "A masterpiece of modern cinema.",
    "Completely forgettable.",
    "The sequel was better.",
    "I expected more from this cast.",
    "Cultural impact is undeniable.",
    "Loved the character development.",
    "Worst ending I've ever seen.",
    "Dialogue felt unnatural.",
    "Soundtrack carried the movie.",
    "Visually stunning, emotionally empty.",
    "Will definitely watch again.",
    "Boring and predictable.",
    "Exceeded my expectations.",
    "Not for everyone.",
    "Impressive world-building.",
    "Left me speechless.",
    "Didn't live up to the hype.",
    "Surprised me in the best way.",
    "Felt like two movies mashed together.",
    "Perfect Sunday night movie.",
    "Painfully long and slow-paced.",
]
